# Configuración de Netlify para FactuBot Landing

[build]
  publish = "."

# Netlify Forms funciona automáticamente detectando el atributo data-netlify="true"
# No se necesita configuración adicional
